---
- debug: msg="Installing prerequisites on system {{ inventory_hostname }}"

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install common apt packages
  apt: pkg={{ item }} state=latest update_cache=true
  with_items: "{{ elk_common_packages }}"
  become: yes

- name: Install Java
  include: java.yml
  tags: [elk]   

- name: ES apt GPG key
  apt_key:
    url='http://packages.elastic.co/GPG-KEY-elasticsearch'
  when: ansible_os_family == 'Debian'
  become: yes

- name: Install Elasticsearch
  include: elasticsearch.yml
  tags: [elk]

- name: Install Nginx
  include: nginx.yml
  tags: [elk]  

- name: Install Kibana
  include: kibana.yml
  tags: [elk]  


#TODO install dashboards
- name: Install Logstash
  include: logstash.yml
  tags: [beats]  
